# Qwen Code CI/CD é›†æˆç¤ºä¾‹
# GitHub Actions å·¥ä½œæµé…ç½®

name: Qwen Code CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Qwen Code CLI
      run: npm install -g @qwen-code/qwen-code@latest
    
    - name: Configure Qwen Code
      env:
        DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
      run: echo "API Key configured"
    
    - name: Code Review - Changed Files
      env:
        DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
      run: |
        git diff --name-only HEAD~1 HEAD | while read file; do
          if [[ "$file" == *.ts || "$file" == *.js || "$file" == *.py ]]; then
            echo "Reviewing: $file"
            qwen -p "å®¡æŸ¥è¿™ä¸ªæ–‡ä»¶çš„ä»£ç è´¨é‡å’Œæ½œåœ¨é—®é¢˜" "$file" --output-format json >> review-results.jsonl
          fi
        done
    
    - name: Upload Review Results
      uses: actions/upload-artifact@v4
      with:
        name: code-review-results
        path: review-results.jsonl

  auto-fix:
    runs-on: ubuntu-latest
    needs: code-review
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Qwen Code CLI
      run: npm install -g @qwen-code/qwen-code@latest
    
    - name: Auto Fix Common Issues
      env:
        DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
      run: |
        # è‡ªåŠ¨ä¿®å¤å¸¸è§é—®é¢˜ï¼ˆéœ€è¦äººå·¥ç¡®è®¤ï¼‰
        qwen -p "è‡ªåŠ¨ä¿®å¤ä»£ç ä¸­çš„å¸¸è§é—®é¢˜ï¼š1) æœªä½¿ç”¨çš„å˜é‡ 2) ç¼ºå°‘é”™è¯¯å¤„ç† 3) ä»£ç æ ¼å¼é—®é¢˜" \
          --auto-fix \
          --dry-run \
          --output-format json > fix-suggestions.json
        
        echo "ä¿®å¤å»ºè®®å·²ç”Ÿæˆï¼Œè¯·åœ¨ PR ä¸­æŸ¥çœ‹"
    
    - name: Create PR Comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'ðŸ¤– Qwen Code å·²å®Œæˆä»£ç å®¡æŸ¥ï¼Œä¿®å¤å»ºè®®å·²ç”Ÿæˆã€‚è¯·æŸ¥çœ‹ Artifacts ä¸‹è½½ review-results.jsonl'
          })

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Qwen Code CLI
      run: npm install -g @qwen-code/qwen-code@latest
    
    - name: Security Scan
      env:
        DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
      run: |
        # å®‰å…¨æ‰«æ
        find src -type f \( -name "*.ts" -o -name "*.js" -o -name "*.py" \) | while read file; do
          qwen -p "å®‰å…¨å®¡æŸ¥ï¼šæ£€æŸ¥ SQL æ³¨å…¥ã€XSSã€æ•æ„Ÿä¿¡æ¯æ³„éœ²ç­‰å®‰å…¨é—®é¢˜" "$file" \
            --output-format json >> security-results.jsonl
        done
    
    - name: Upload Security Results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: security-results.jsonl
